### ISSUE TITLE
Doesnt work for DNX Rc1

### ISSUE THREAD

**Issue by vadim82** [giggio/FluentMigrator.Runner.DNX#16]
using the global command 

``` shell
fm --connectionString "Data Source=(local);User ID=***;Password=***;Initial Catalog=***;MultipleActiveResultSets=True;" --provider sqlserver2012
```

results in the following error

``` shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentMigrator.Runner.DNX.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by giggio** [comment]
Also published to nuget.org.
